services:
  news-service:
    build: ./news-service
    ports:
      - "8003:8003"
    volumes:
      - ./news-service/app:/app/app
      - ./news-service/requirements.txt:/app/requirements.txt
    env_file:
      - ./news-service/.env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - lif-network

  sasb-service:
    build: ./sasb-service
    ports:
      - "8004:8004"
    volumes:
      - ./sasb-service/app:/app/app
      - ./sasb-service/requirements.txt:/app/requirements.txt
    env_file:
      - ./sasb-service/.env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - lif-network

  issuepool-service:
    build: ./issuepool-service
    ports:
      - "8005:8005"
    volumes:
      - ./issuepool-service/app:/app/app
      - ./issuepool-service/requirements.txt:/app/requirements.txt
    env_file:
      - ./issuepool-service/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    networks:
      - lif-network
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    volumes:
      - ./gateway:/app
    env_file:
      - ./gateway/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    depends_on:
      - news-service
      - sasb-service
      - issuepool-service
    networks:
      - lif-network
networks:
  lif-network:
    driver: bridge